### PR TITLE
Integrate fixes

### PR DESCRIPTION
**Pull request by janderse**
To integrate:
- [x] Update ParsePacer.py to handle relative links.
- [x] Remove unused commented lines from ParsePacer.py as requested by Dhruv
- [ ] Fix unit tests and breakage from removing secrets
- [ ] Split up alltests.py into separate unit test files.
- [ ] Parse dockets where parties are spread across multiple tables

### CODE REVIEW

**Comment by mlissner** [comment]
@dkapadia, @janderse, I'm cleaning up some old pull requests. It looks like there's some good code in here. Is it worth figuring out and getting it merged? @dkapadia would you be willing to wrap up reviewing this or should I try to take it over?

**Comment by janderse** [comment]
At this point I would recommend only pulling in the bit for parsing dockets where parties are spread across multiple tables.

The other stuff is probably fairly out of date (splitting up the unit tests and settings stuff).

There might be some git-fu that could pull apart just that one commit?  Maybe if I did some history revision on my branch?  I'm not a git expert yet.

**Comment by mlissner** [comment]
If you wouldn't mind doing that, I'd definitely appreciate it. Looks like an automatic merge can't happen at this point anyway.

**Comment by mlissner** [comment]
Closing this. This code is now deprecated.

**Pull request closed without merging**
