### PR TITLE
Rework settings

### PR DESCRIPTION
**Pull request by audiodude**
Based on the setup here: https://github.com/freelawproject/courtlistener/blob/master/alert/settings.py

This change makes it easier to setup servers with divergent settings, including
dev servers. It also documents some of the more "secret" settings in the app.
Finally, it merges the concept of "recap_config" directly into Django's own
settings system, so there is only one source of all settings and one place for
settings to be overridden no matter what "type" they are (DB config versus IA
urls).

### CODE REVIEW

**Comment by audiodude** [comment]
Note that there was some weird git voodoo going on here. But I launched more voodoo at it and apparently fixed it.

**Comment by mlissner** [comment]
I won't have time to look at this properly until Wednesday, but I wonder if you might pull out some upgrade notes. In theory, I usually keep [a file around in my repos][1] for this purpose, but hadn't created one in this repo just yet. This seems like a big enough tweak to the installations that some upgrade notes might be useful, if you don't mind kicking that off?

[1]: https://github.com/freelawproject/courtlistener/blob/master/upgrade.txt

**Comment by mlissner** [comment]
OK, I couldn't help myself and I went ahead and read through this. Good stuff. Two minor thoughts:

0. This is lame, I do try to keep things cleanish going forward. I think you've got two spaces in some py files and four in others. Mind tweaking?
0. I like the secret_key generation thing. Where'd you get that pattern?

**Comment by audiodude** [comment]
Okay I fixed the indents, and I'm working on the UPGRADING guide.

The secret_key pattern came from: http://stackoverflow.com/questions/4664724/distributing-django-projects-with-unique-secret-keys

**Comment by audiodude** [comment]
I've added the upgrade guide as UPGRADING.md. PTAL, thanks!

**Comment by mlissner** [comment]
Looks like great notes. Tomorrow I should have time to pull this code into the dev machine, merge it there, then test the upgrade notes, make any changes I notice and then push it all back here.

**Comment by mlissner** [comment]
This is all merged. Ran into a dumb issue with the `with` statement and Python 2.5, but easily fixed it with:

    from __future__ import with_statement

Ugh. Can't want to get this server upgraded.

**Comment by audiodude** [comment]
Awesome!

It should be:
```
from __present__ import with_statement
```

O_o

**Pull request merged**
